### ISSUE TITLE
Extra padding if row is complete

### ISSUE THREAD

**Issue by IronicallyJesus** [flavienlaurent/colorpicker#1]
As you see from the screenshots, if the row is completed, extra padding is added below the color palette which makes it less appealing. 
![screenshot_2013-07-17-23-53-31](https://f.cloud.github.com/assets/3488086/816964/0bd5735a-ef5f-11e2-81e6-755b6fbbca90.png)
![screenshot_2013-07-17-23-52-52](https://f.cloud.github.com/assets/3488086/816965/0bd86006-ef5f-11e2-93ec-da86ce38dbc7.png)

**Comment by flavienlaurent** [comment]
FYI ColorPicker is now open source https://android.googlesource.com/platform/frameworks/opt/colorpicker/

you issue ee55537eb4c67c47fcd90e6e682d42f1d99a5f6c
